### PR TITLE
REverted to default surefire report path

### PR DESCRIPTION
**Pull request by ampie**

### CODE REVIEW

**Comment by ampie** [comment]
[52% (0.0%) vs master 52%](https://jenkins.entandocloud.com/job/de-entando-de-app-pr/2/)

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Pull request merged**
